config/routes.rb
Rails.application.routes.draw do

  if Settings.multitenancy.enabled
    constraints host: Account.admin_host do
      get '/account/sign_up' => 'account_sign_up#new', as: 'new_sign_up'
      post '/account/sign_up' => 'account_sign_up#create'
      get '/', to: 'splash#index'

      # pending https://github.com/projecthydra-labs/hyrax/issues/376
      get '/dashboard', to: redirect('/')

      namespace :proprietor do
        resources :accounts
      end
    end
  end

  get 'status', to: 'status#index'

  mount BrowseEverything::Engine => '/browse'
  resource :site, only: [:update] do
    resources :roles, only: [:index, :update]
    resource :labels, only: [:edit, :update]
  end

  root 'hyrax/homepage#index'

  devise_for :users, controllers: { invitations: 'hyku/invitations', registrations: 'hyku/registrations' }
  mount Qa::Engine => '/authorities'

  mount Blacklight::Engine => '/'
  mount Hyrax::Engine, at: '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  curation_concerns_basic_routes do
    member do
      get :manifest
    end
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  namespace :admin do
    resource :account, only: [:edit, :update]
    resources :users, only: [:destroy]
    resources :groups do
      member do
        get :remove
      end

      resources :users, only: [:index], controller: 'group_users' do
        collection do
          post :add
          delete :remove
        end
      end
    end
  end

  mount Peek::Railtie => '/peek'
  mount Riiif::Engine => '/images', as: 'riiif'
end

app/controllers/account_sign_up_controller.rb
class AccountSignUpController < ProprietorController
  load_and_authorize_resource instance_name: :account, class: 'Account'

  before_action :ensure_admin!, if: :admin_only_tenant_creation?

  # GET /account/sign_up
  def new
    add_breadcrumb t(:'hyrax.controls.home'), root_path
    add_breadcrumb 'New account', new_sign_up_path
  end

  # POST /account/sign_up
  # POST /account/sign_up.json
  def create
    respond_to do |format|
      if CreateAccount.new(@account).save
        format.html { redirect_to first_user_registration_url, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account.cname }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def ensure_admin!
      # Require Admin access to perform any actions
      authorize! :read, :admin_dashboard
    end

    def admin_only_tenant_creation?
      Settings.multitenancy.admin_only_tenant_creation
    end

    def first_user_registration_url
      new_user_registration_url(host: @account.cname)
    end

    def create_params
      params.require(:account).permit(:name)
    end
end

app/views/account_sign_up/new.html.erb
<% content_for :page_header do %>
  <h1><span class="fa fa-gears"></span> Create a new repository</h1>
<% end %>

<div class="row">
  <div class="col-md-8">
    <%= form_for(@account, url: account_sign_up_path(@account), html: { class: 'form form-horizontal' }) do |f| %>
        <% if @account.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <%= pluralize(@account.errors.count, "error") %> prohibited this repository from being saved:
            <ul>
            <% @account.errors.messages.each do |key, messages| %>
              <li><%= key %> &quot;<%= @account.errors.details[key].first[:value] %>&quot; <%= messages.join(' and ') %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name, 'Short name', class: 'col-md-2 control-label' %>
          <div class="col-md-10">
            <%= f.text_field :name, class: 'form-control' %>
            <span class="help-block">A single or hyphenated name used for technical aspects of the repository (e.g., "acme" or "acme-library").</span>
          </div>
        </div>

        <%= f.submit class: 'btn btn-primary pull-right' %>
      <% end %>
  </div>
</div>