config/routes.rb
Rails.application.routes.draw do

  if Settings.multitenancy.enabled
    constraints host: Account.admin_host do
      get '/account/sign_up' => 'account_sign_up#new', as: 'new_sign_up'
      post '/account/sign_up' => 'account_sign_up#create'
      get '/', to: 'splash#index'

      # pending https://github.com/projecthydra-labs/hyrax/issues/376
      get '/dashboard', to: redirect('/')

      namespace :proprietor do
        resources :accounts
      end
    end
  end

  get 'status', to: 'status#index'

  mount BrowseEverything::Engine => '/browse'
  resource :site, only: [:update] do
    resources :roles, only: [:index, :update]
    resource :labels, only: [:edit, :update]
  end

  root 'hyrax/homepage#index'

  devise_for :users, controllers: { invitations: 'hyku/invitations', registrations: 'hyku/registrations' }
  mount Qa::Engine => '/authorities'

  mount Blacklight::Engine => '/'
  mount Hyrax::Engine, at: '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  curation_concerns_basic_routes do
    member do
      get :manifest
    end
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  namespace :admin do
    resource :account, only: [:edit, :update]
    resources :users, only: [:destroy]
    resources :groups do
      member do
        get :remove
      end

      resources :users, only: [:index], controller: 'group_users' do
        collection do
          post :add
          delete :remove
        end
      end
    end
  end

  mount Peek::Railtie => '/peek'
  mount Riiif::Engine => '/images', as: 'riiif'
end

app/controllers/labels_controller.rb
class LabelsController < SitesController
  # GET /sites/1/edit
  def edit
    add_breadcrumb t(:'hyrax.controls.home'), root_path
    add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
    add_breadcrumb t(:'hyrax.admin.sidebar.configuration'), '#'
    add_breadcrumb t(:'hyrax.admin.sidebar.labels'), edit_site_labels_path
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to edit_site_labels_path, notice: 'Labels were successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:application_name,
                                   :institution_name,
                                   :institution_name_full)
    end
end

app/views/labels/edit.html.erb
<% content_for :page_header do %>
  <h1><span class="fa fa-institution"></span> <%= t(:'hyrax.admin.sidebar.labels') %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <%= form_for(@site, url: site_labels_path) do |f| %>
        <div class="panel-heading">
          <h3 class="panel-title">General Repository Labels</h3>
        </div>
        <div class="panel-body">
          <% if @site.errors.any? %>
              <div id="error_explanation">
                  <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

                  <ul>
                      <% @site.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                  </ul>
              </div>
          <% end %>
          <div class="field form-group">
              <%= f.label :application_name %><br>
              <%= f.text_field :application_name, class: 'form-control'%>
          </div>

          <div class="field form-group">
              <%= f.label :institution_name %><br>
              <%= f.text_field :institution_name, class: 'form-control'%>
          </div>

          <div class="field form-group">
              <%= f.label :institution_name_full %><br>
              <%= f.text_field :institution_name_full, class: 'form-control'%>
          </div>
        </div>
        <div class="panel-footer">
          <%= f.submit class: 'btn btn-primary pull-right' %>
        </div>
      <% end %>
    </div>
  </div>
</div>