config/routes.rb
Rails.application.routes.draw do

  if Settings.multitenancy.enabled
    constraints host: Account.admin_host do
      get '/account/sign_up' => 'account_sign_up#new', as: 'new_sign_up'
      post '/account/sign_up' => 'account_sign_up#create'
      get '/', to: 'splash#index'

      # pending https://github.com/projecthydra-labs/hyrax/issues/376
      get '/dashboard', to: redirect('/')

      namespace :proprietor do
        resources :accounts
      end
    end
  end

  get 'status', to: 'status#index'

  mount BrowseEverything::Engine => '/browse'
  resource :site, only: [:update] do
    resources :roles, only: [:index, :update]
    resource :labels, only: [:edit, :update]
  end

  root 'hyrax/homepage#index'

  devise_for :users, controllers: { invitations: 'hyku/invitations', registrations: 'hyku/registrations' }
  mount Qa::Engine => '/authorities'

  mount Blacklight::Engine => '/'
  mount Hyrax::Engine, at: '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  curation_concerns_basic_routes do
    member do
      get :manifest
    end
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  namespace :admin do
    resource :account, only: [:edit, :update]
    resources :users, only: [:destroy]
    resources :groups do
      member do
        get :remove
      end

      resources :users, only: [:index], controller: 'group_users' do
        collection do
          post :add
          delete :remove
        end
      end
    end
  end

  mount Peek::Railtie => '/peek'
  mount Riiif::Engine => '/images', as: 'riiif'
end

app/models/user.rb
class User < ApplicationRecord
  # Includes lib/rolify from the rolify gem
  rolify
  # Connects this user object to Hydra behaviors.
  include Hydra::User
  # Connects this user object to Hyrax behaviors.
  include Hyrax::User
  include Hyrax::UserUsageStats

  attr_accessible :email, :password, :password_confirmation if Blacklight::Utils.needs_attr_accessible?
  # Connects this user object to Blacklights Bookmarks.
  include Blacklight::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :add_default_roles

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier.
  def to_s
    email
  end

  def site_roles
    roles.site
  end

  def site_roles=(roles)
    roles.reject!(&:blank?)

    existing_roles = site_roles.pluck(:name)
    new_roles = roles - existing_roles
    removed_roles = existing_roles - roles

    new_roles.each do |r|
      add_role r, Site.instance
    end

    removed_roles.each do |r|
      remove_role r, Site.instance
    end
  end

  def groups
    return ['admin'] if has_role?(:admin, Site.instance)
    []
  end

  private

    def add_default_roles
      add_role :admin, Site.instance unless self.class.any? || Account.global_tenant?
    end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :load_user, only: [:destroy]

    # NOTE: User creation/invitations handled by devise_invitable

    # Delete a user from the site
    def destroy
      if @user.present? && @user.destroy
        redirect_to hyrax.admin_users_path, notice: t('hyrax.admin.users.destroy.success', user: @user)
      else
        redirect_to hyrax.admin_users_path flash: { error: t('hyrax.admin.users.destroy.failure', user: @user) }
      end
    end

    private

      def load_user
        @user = User.from_url_component(params[:id])
      end
  end
end

app/views/hyrax/admin/users/index.html.erb
<% provide :page_header do %>
  <h1><span class="fa fa-user"></span> <%= t('hyrax.admin.users.index.title') %></h1>
<% end %>

<div class="panel panel-default users-invite">
  <div class="panel-heading">
      <%= t('.invite_users') %>
  </div>
  <div class="panel-body">
      <%# user_invitation_path is provided by devise_invitable %>
      <%= simple_form_for :user,  url: main_app.user_invitation_path, html: { class: 'form-inline pull-left' } do |f| %>
        <div class="form-group">
          <%= f.hint :email %>
          <%= f.label :email, class: "control-label", required: false %>
          <%= f.input_field :email, class: "form-control", value: "" %>
          <%= f.submit t('.add'), class: 'btn btn-primary' %>
        </div>
      <% end %>
  </div>
</div>

<div class="panel panel-default users-listing">
  <div class="panel-heading">
      <%= t('hyrax.admin.users.index.describe_users_html', count: @presenter.user_count) %>
  </div>

  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped datatable">
        <thead>
          <tr>
            <th></th>
            <th><%= t('.id_label') %></th>
            <th><%= t('.role_label') %></th>
            <th><%= t('.access_label') %></th>
            <th><%= t('.status_label') %></th>
            <th><%= t('.action_label') %></th>
          </tr>
        </thead>
        <tbody>
          <% @presenter.users.each do |user| %>
            <tr>
              <td><%= link_to hyrax.user_path(user) do %>
                    <%= image_tag(user.avatar.url(:thumb), width: 30) if user.avatar.file %>
                  <% end %>
              </td>
              <td><%= link_to user.email, hyrax.user_path(user) %></td>
              <td><% roles = @presenter.user_roles(user) %>
                  <ul><% roles.each do |role| %>
                    <li><%= role %></li>
                    <% end %>
                  </ul>
              </td>
              <td>
                <%# in the case that a user is created who never signs in, this is necessary %>
                <relative-time datetime="<%= @presenter.last_accessed(user).getutc.iso8601 %>" title="<%= @presenter.last_accessed(user).to_formatted_s(:standard) %>">
                  <%= @presenter.last_accessed(user).to_formatted_s(:long_ordinal) %>
                </relative-time>
              </td>
              <%# If user accepted invite or was a self-signup, they are active. Otherwise pending %>
              <td><%= user.accepted_or_not_invited? ? t('.status.active') : t('.status.pending') %></td>
              <td>
                <%= link_to t('.delete'),  main_app.admin_user_path(user), class: 'btn btn-danger btn-sm action-delete', method: :delete, data: { confirm: t('hyrax.admin.users.destroy.confirmation', user: user.email) } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>